spring.application.name=gestor-gastos-personales-api

# ===============================
# Configuracion de Base de Datos PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_gastos_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion del pool HikariCP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# ===============================
# Configuracion JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_schema=public

# ===============================
# Configuracion del servidor
# ===============================
server.port=8080
server.servlet.context-path=/api
server.error.include-message=always
server.error.include-binding-errors=always


# JasperReports
jasper.reports.path=classpath:reports/templates/
jasper.reports.compiled.path=classpath:reports/compiled/
jasper.reports.logo.path=classpath:reports/images/logo.png
jasper.reports.watermark.path=classpath:reports/images/watermark.png

# Informacion del aplicativo
app.name=Gestor de Gastos Personales
app.version=1.0.0
app.author=JSCA